"$schema" = 'https://starship.rs/config-schema.json'


[cmd_duration]
min_time = 5

[directory]
truncation_length = 4
truncate_to_repo = true

[git_status]
style = "bold white"
untracked = "✦"
staged = "●"
modified = "⊙"
renamed = "↪"
deleted = "✘"
stashed = "⚑"
conflicted = "⁉"
ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"


[character]
success_symbol = '[\$](bold)'
