## Reference: https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $cmd_duration
$character
"""

[cmd_duration]
min_time = 5_000

[directory]
truncation_symbol = '…/'
truncation_length = 1
truncate_to_repo = true
fish_style_pwd_dir_length = 3

[directory.substitutions]
# '/Users/sb/src/iagl/apimgmt-devportal-partner-management' = 'pm'
# '$HOME/src/iagl' = 'iagl'

[git_status]
style = "bold white"
untracked = "✦"
staged = "●"
modified = "⊙"
renamed = "↪"
deleted = "✘"
stashed = "⚑"
conflicted = "⁉"
ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 6
format = '[:$hash]($style) '
only_detached = false

[character]
success_symbol = '[\$]()'
error_symbol = '[\$](bold red)'
