tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "kryptco/tap"
tap "wagoodman/dive"
brew "azure-cli"
brew "bash"
brew "bat"
brew "bitwarden-cli"
brew "choose-gui"
brew "clojure"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "exa"
brew "fd"
brew "findutils"
brew "ghq"
brew "git"
brew "git-cal"
brew "git-crypt"
brew "hostess"
brew "htop"
brew "httpie"
brew "httpstat"
brew "hub"
brew "icdiff"
brew "jq"
brew "kubernetes-cli"
brew "leiningen"
brew "lftp"
brew "loc"
brew "m-cli"
brew "mas"
brew "mitmproxy"
brew "moreutils"
brew "ncdu"
brew "neovim"
brew "nvm"
brew "peco"
brew "pv"
brew "rename"
brew "ripgrep"
brew "rust"
brew "rustup-init"
brew "shellcheck"
brew "tee-clc"
brew "tig"
brew "tree"
brew "vim"
brew "watch"
brew "wifi-password"
brew "zsh"
brew "heroku/brew/heroku"
brew "wagoodman/dive/dive"
cask "alfred"
cask "appcleaner"
cask "bitwarden"
cask "cyberduck"
cask "dbeaver-community"
cask "docker-edge"
cask "dropbox"
cask "evernote"
cask "fantastical"
cask "firefox"
cask "font-fira-code"
cask "franz"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "graphql-playground"
cask "helium"
cask "imageoptim"
cask "iterm2"
cask "java8"
cask "karabiner-elements"
cask "keepassxc"
cask "keybase"
cask "kitty"
cask "mailspring"
cask "ngrok"
cask "numi"
cask "onedrive"
cask "oni"
cask "osxfuse"
cask "pgadmin4"
cask "postman"
cask "qlstephen"
cask "rambox"
cask "skitch"
cask "softu2f"
cask "sonos"
cask "spotify"
cask "standard-notes"
cask "steam"
cask "textexpander"
cask "torbrowser"
cask "trailer"
cask "transmission"
cask "typinator"
cask "viscosity"
cask "visual-studio-code"
mas "Airmail 3", id: 918858936
mas "BetterSnapTool", id: 417375580
mas "Boxy", id: 1053031090
mas "DaisyDisk", id: 411643860
mas "Dice Pass", id: 997688302
mas "Fenêtre", id: 1286743037
mas "Folder Tidy", id: 486626129
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "Shazam", id: 897118787
mas "Xcode", id: 497799835
