tap "apenngrace/vulkan"
tap "aws/tap"
tap "clojure/tools"
tap "dart-lang/dart"
tap "equalsraf/neovim-qt"
tap "eth-p/software"
tap "helix-editor/helix"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "kryptco/tap"
tap "railwaycat/emacsmacport"
tap "rogual/neovim-dot-app"
tap "schniz/tap"
tap "tavianator/tap"
tap "trinitronx/pcloud"
tap "uptech/oss"
tap "wagoodman/dive"
# Text processing scripting language
brew "awk"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# New way to see and navigate directory trees
brew "broot"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Power of curl, ease of use of httpie
brew "curlie"
# Modern diagram scripting language that turns text to diagrams
brew "d2"
# Command-line DNS client
brew "dog"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Collection of GNU find, xargs, and locate
brew "findutils"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Fast and simple Node.js version manager
brew "fnm"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Enable transparent encryption/decryption of files in a git repo
brew "git-crypt"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Incremental merge for git
brew "git-imerge"
# Rebase alternative for easy & efficient in-memory rebases and fixups
brew "git-revise"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Ping, but with a graph
brew "gping"
# Generic library support script
brew "libtool"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Curl statistics made simple
brew "httpstat"
# Add GitHub support to git on the command-line
brew "hub"
# Configurable static site generator
brew "hugo"
# Get events and tasks from the macOS calendar database
brew "ical-buddy"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Terminal file manager
brew "lf"
# Count lines of code quickly
brew "loc"
# Package manager for the Lua programming language
brew "luarocks"
# Swiss Army Knife for macOS
brew "m-cli"
# Mac App Store command-line interface
brew "mas"
# Java-based project management
brew "maven"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# NCurses Disk Usage
brew "ncdu"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Control nvim processes using `nvr` command-line tool
brew "neovim-remote"
# Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
brew "prettier"
# Command-line YAML and XML processor that wraps jq
brew "python-yq"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Rust toolchain installer
brew "rustup-init"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Text interface for Git repositories
brew "tig"
# Simplified and community-driven man pages
brew "tldr"
# CLI tool that moves files or folder to the trash
brew "trash"
# Friendly and fast tool for sending HTTP requests
brew "xh"
# Fast CSV toolkit written in Rust
brew "xsv"
# JavaScript package manager
brew "yarn"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Bash scripts that integrate bat with various command-line tools
brew "eth-p/software/bat-extras"
# Breadth-first version of find.
brew "tavianator/tap/bfs"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Application uninstaller
cask "appcleaner"
# Web browser focusing on privacy
cask "brave-browser"
# Voice and text chat software
cask "discord"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
# Screen color temperature controller
cask "flux"
# Unofficial 'light' native application for Fastmail
cask "fmail2"
# Legible monospace font
cask "font-comic-mono"
# Free monospaced font with programming ligatures
cask "font-fira-code"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# Monospaced typeface designed for programming in Julia
cask "font-juliamono"
# Finder replacement and FTP, SFTP, WebDAV and Amazon s3 client
cask "forklift"
# Utility to provide quick look previews for files that aren't natively supported
cask "glance-chamburr"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Optimise and personalise your Jabra headset
cask "jabra-direct"
# Keyboard customizer
cask "karabiner-elements"
# Display key code, unicode value and modifier keys state for any key combination
cask "key-codes"
# File system integration
cask "macfuse"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Online collaborative whiteboard platform
cask "miro"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Utility to move and zoom windows—on one display
cask "moom"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Cloud-based, multi-factor authentication
cask "pingid"
# Collaboration platform for API development
cask "postman"
# Control your tools with a few keystrokes
cask "raycast"
# Instant messaging application focusing on security
cask "signal"
# Team communication and collaboration software
cask "slack"
# Control your Sonos system
cask "sonos"
# Music streaming service
cask "spotify"
# OpenVPN client with AppleScript support
cask "viscosity"
# Open-source code editor
cask "visual-studio-code"
# Desktop client for WhatsApp
cask "whatsapp"
# Video communication and virtual meeting platform
cask "zoom"
mas "Airmail", id: 918858936
mas "Commander One", id: 1035236694
mas "DaisyDisk", id: 411643860
mas "DiceGen", id: 980521593
mas "Folder Tidy", id: 486626129
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iPreview", id: 1519213509
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Meeter", id: 1510445899
mas "Menu Bar Controller for Sonos", id: 1357379892
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "rcmd", id: 1596283165
mas "Shazam", id: 897118787
mas "Todoist", id: 585829637
