vim.opt.autoindent     = true -- enable autoindent
vim.opt.background = "light"
vim.opt.backup         = false -- disable backup
vim.opt.cursorline     = true -- enable cursorline
vim.opt.expandtab      = true -- use spaces instead of tabs
vim.opt.autowrite      = true -- autowrite buffer when it's not focused
vim.opt.hidden         = true -- keep hidden buffers
vim.opt.hlsearch       = true -- don't highlight matching search
vim.opt.ignorecase     = true -- case insensitive on search
vim.opt.lazyredraw     = true -- lazyredraw to make macro faster
vim.opt.list           = true -- display listchars
  -- number         = true, -- enable number
  -- relativenumber = true, -- enable relativenumber
vim.opt.showmode       = false -- don't show mode
vim.opt.smartcase      = true -- improve searching using '/'
vim.opt.smartindent    = true -- smarter indentation
vim.opt.smarttab       = true -- make tab behaviour smarter
vim.opt.splitbelow     = true -- split below instead of above
vim.opt.splitright     = true -- split right instead of left
vim.opt.startofline    = false -- don't go to the start of the line when moving to another file
vim.opt.swapfile       = false -- disable swapfile
vim.opt.termguicolors  = true -- truecolours for better experience
vim.opt.wrap           = false -- dont wrap lines
vim.opt.writebackup    = false -- disable backup
vim.opt.backupcopy     = "yes" -- fix weirdness for stuff that replaces the entire file when hot reloading
vim.opt.completeopt    = { "menu", "menuone", "noselect", "noinsert" } -- better completion
vim.opt.encoding       = "UTF-8" -- set encoding
vim.opt.fillchars      = {
  vert = "│",
  eob = " ",
  fold = " ", 
} -- make vertical split sign better
vim.opt.foldmethod     = "marker"
  -- foldexpr       = "nvim_treesitter#foldexpr()",
  -- foldlevel      = 0, -- don't fold anything if I don't tell it to do so
  -- foldnestmax    = 1, -- only allow 1 nested folds, it can be confusing if I have too many
vim.opt.foldopen       = "percent,search" -- don't open fold if I don't tell it to do so
  -- foldcolumn     = "1", -- enable fold column for better visualisation
vim.opt.inccommand     = "split" -- incrementally show result of command
vim.opt.listchars      = { eol = "↲", tab= "» " } -- set listchars
vim.opt.mouse          = "a" -- enable mouse support
vim.opt.shortmess      = "csa" -- disable some stuff on shortmess
vim.opt.signcolumn     = "yes" -- enable sign column all the time, 4 column
vim.opt.shell          = "/usr/bin/bash" -- use bash instead of zsh
-- vim.opt.colorcolumn    = { "80" } -- 80 chars color column
vim.opt.colorcolumn    = { } -- no color column
vim.opt.laststatus     = 2 -- always enable statusline
vim.opt.pumheight      = 10 -- limit completion items
vim.opt.re             = 0 -- set regexp engine to auto
vim.opt.scrolloff      = 2 -- make scrolling better
vim.opt.sidescroll     = 2 -- make scrolling better
vim.opt.shiftwidth     = 2 -- set indentation width
vim.opt.sidescrolloff  = 15 -- make scrolling better
vim.opt.tabstop        = 2 -- tabsize
vim.opt.timeoutlen     = 400 -- faster timeout wait time
vim.opt.updatetime     = 100 -- set faster update time

