#!/bin/bash
if [ -z "$SSH_TUNNEL_PID" ]; then
  echo "No tunnel to close"
  return
fi
echo "Closing SSH tunnel.."
kill $SSH_TUNNEL_PID >/dev/null
if [ $? -ne 0 ]; then
  echo "Failed to kill SSH tunnel with PID $SSH_TUNNEL_PID"
  return 1
fi
