#!/bin/bash
if [[ "$1" == '-h' ]] || [ -z "$1" ]; then
  echo '`killport <PORT>` finds the process listening to the specified port and kills it.'
else
  process_line=$(lsof -i ":$1" | tail -1)
  if [[ "$process_line" == "" ]]; then
      echo "no processes listening on $1"
  else
      process_name=`echo "$process_line" | awk '{print $1}'`
      echo "killing $process_name"
      kill `echo "$process_line" | awk '{print $2}'`
  fi
fi
