#!/bin/bash

set -x
P="$(pwd)"
PC=("${(@s|/|)P}")

MIN=2
CURPATH=
SHOWPATH=
for D in $PC; do
  echo : $D
  PREFIX=$(cd "${CURPATH:-/}" && find . -type d -maxdepth 1 | grep -C1 "$D" | cut -c3- | sed -e 'N;s/^\(.*\).*\n\1.*$/\1/')
  CHARS=$(( MIN > ${#PREFIX} ?  MIN : ${#PREFIX} + 1 ))
  # CHARS=$(cd "$CURPATH" && find . -type d -maxdepth 1 | cut -c3- | sed -e 'N;s/^\(.*\).*\n\1.*$/\1/' | wc -m | tr -d '[:space:]')
  SHOWPATH="${SHOWPATH}/${D[1,CHARS]}"
  CURPATH="$CURPATH/$D"
done

