- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true

- link:
    ~/.config/fish: fish
    ~/.config/kitty: kitty
    ~/.config/nvim: vim
    ~/.config/yarn/global/package.json: dotfiles/package.json
    ~/.ripgreprc: dotfiles/ripgreprc
    ~/.curlrc: dotfiles/curlrc.ini
    $PROJECTS/.editorconfig: dotfiles/editorconfig.ini
    ~/.gitconfig: dotfiles/gitconfig.ini
    ~/.gitignore: dotfiles/gitignore.txt
    ~/.hushlogin: dotfiles/hushlogin.txt
    ~/.ignore: dotfiles/ignore.txt
    ~/.p10k.zsh: dotfiles/p10k.zsh
    ~/.spacemacs: dotfiles/spacemacs.el
    ~/.tigrc: dotfiles/tigrc.ini
    ~/.vim: vim
    ~/.zshrc: dotfiles/zshrc.zsh
    ~/.zshenv: dotfiles/zshenv.zsh

- clean:
    - "~"
    - "$PROJECTS"

- shell:
    - description: Updating Homebrew repository
      command: brew update
    - description: Upgrading Homebrew packages
      command: brew upgrade --fetch-HEAD
    - description: Recording current Homebrew state
      command: brew bundle dump --describe --force
    - description: Cleaning up
      command: brew cleanup
    - description: Upgrading global npm packages
      command: yarn global upgrade --latest
    - description: Updating ZSH for Humans
      command: zsh -ic 'z4h update'
