- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true

- link:
    ~/.config/fish: fish
    ~/.config/kitty: kitty
    ~/.config/nvim: vim
    ~/.config/yarn/global/package.json: dotfiles/package.json
    ~/.config/starship.toml: dotfiles/starship.toml
    ~/.ripgreprc: dotfiles/ripgreprc
    ~/.curlrc: dotfiles/curlrc.ini
    ~/docker-compose.yml: dotfiles/docker-compose.yml
    $PROJECTS/.editorconfig: dotfiles/editorconfig.ini
    ~/.gitconfig: dotfiles/gitconfig.ini
    ~/.gitignore: dotfiles/gitignore.txt
    ~/.gnupg/gpg.conf: dotfiles/gpg.conf
    ~/.hushlogin: dotfiles/hushlogin.txt
    ~/.hgrc: dotfiles/hgrc.ini
    ~/.ignore: dotfiles/ignore.txt
    ~/.npmrc: dotfiles/npmrc.ini
    ~/.spacemacs: dotfiles/spacemacs.el
    ~/.skhdrc: dotfiles/skhdrc.ini
    ~/.tigrc: dotfiles/tigrc.ini
    ~/.yabairc: dotfiles/yabairc.sh
    ~/.vim: vim

- clean:
    - "~"
    - "$PROJECTS"

- shell:
    - description: Updating Homebrew repository
      command: brew update
    - description: Upgrading Homebrew packages
      command: brew upgrade
    - description: Recording current Homebrew state
      command: brew bundle dump --describe --force
    - description: Cleaning up
      command: brew cleanup
    - description: Upgrading global npm packages
      command: yarn global upgrade --latest
    - description: Upgrading fish shell plugins
      command: fisher

