- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
      stderr: true

- link:
    ~/.chunkwmrc: dotfiles/chunkwmrc.sh
    ~/.config/fish: fish
    ~/.config/kitty: kitty
    ~/.config/nvim: vim
    ~/.ripgreprc: dotfiles/ripgreprc
    ~/.vim: vim
    ~/.vimrc: vim/init.vim
    ~/.curlrc: dotfiles/curlrc.ini
    ~/docker-compose.yml: dotfiles/docker-compose.yml
    # ~/.editorconfig: dotfiles/editorconfig.ini
    ~/.gitconfig: dotfiles/gitconfig.ini
    ~/.gitignore: dotfiles/gitignore.txt
    ~/.gnupg/gpg.conf: dotfiles/gpg.conf
    # Hushes the default "Last login" message on macos
    ~/.hushlogin: dotfiles/hushlogin.txt
    ~/.hgrc: dotfiles/hgrc.ini
    ~/.ignore: dotfiles/ignore.txt
    ~/.npmrc: dotfiles/npmrc.ini
    ~/.spacemacs: dotfiles/spacemacs.el
    ~/.skhdrc: dotfiles/skhdrc.ini
    ~/.tigrc: dotfiles/tigrc.ini
    # Note this link is not actually in use, but the target file _is_.
    ~/.zhistory: zhistory.txt
    ~/.zshrc: dotfiles/zshrc.zsh

- clean:
    - "~"
    - "$PROJECTS"

- shell:
    - description: Updating Homebrew
      command: brew update
    - description: Upgrading software
      command: brew upgrade
    - command: brew bundle check --file=Brewfile.sh || brew bundle --file=Brewfile.sh
      description: Installing software
    - command: yarn global upgrade --latest
      description: Upgrading global npm packages
    - command: brew cleanup
      description: Cleaning up
